# Generated by Django 4.1.4 on 2023-02-07 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_comment_commentss'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='News_or_Article',
            field=models.TextField(default='Ожидается'),
        ),
    ]
