# Generated by Django 4.1.4 on 2023-02-07 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_post_news_or_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Article',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='News',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='News_or_Article',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
