# Generated by Django 4.1.4 on 2023-02-07 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_post_article_alter_post_news_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='News_or_Article',
        ),
    ]
