# Generated by Django 4.1.4 on 2023-02-07 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_post_article_alter_post_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='About_everything_new',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
